sonar.projectKey=stephenlclarke_grpc-swift-nio-transport
sonar.organization=stephenlclarke
sonar.projectName=grpc-swift-nio-transport
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8
sonar.sources=Sources
sonar.tests=Tests
sonar.test.inclusions=Tests/**/*.swift
sonar.exclusions=.build/**,**/*.generated.swift
sonar.coverage.exclusions=Sources/CGRPCNIOTransportZlib/**
sonar.coverageReportPaths=coverage.xml
sonar.qualitygate.wait=true
